version: "2.1"

services:
  nginx:
    container_name: hackershall-dev-nginx
    image: nginx-dev-i
    build:
      context: ./hyndsite/docker4devs-react-mongo-compose
      dockerfile: ./.docker/nginx.dev.dockerfile
    networks:
      - hackershall-network
    links:
      - node:node
    ports:
      - "80:80"

  node:
    container_name: hackershall-dev-app
    image: hackershall-dev-i
    build:
      context: ./hyndsite/docker4devs-react-mongo-compose
      dockerfile: ./.docker/node.dev.dockerfile
    ports:
      - "7000"
    networks:
      - hackershall-network
    volumes:
      - ./hyndsite/docker4devs-react-mongo-compose:/var/app
    env_file:
      - ./hyndsite/docker4devs-react-mongo-compose/.docker/env/app.dev.env
    working_dir: /var/app

  mongo:
    container_name: hackershall-dev-mongodb
    image: mongo:3.4.1
    build:
      context: ./hyndsite/docker4devs-react-mongo-compose
      dockerfile: ./.docker/mongo.dev.dockerfile
    env_file:
      - ./hyndsite/docker4devs-react-mongo-compose/.docker/env/mongo.dev.env
    networks:
      - hackershall-network
    ports:
      - "27017"

networks:
  hackershall-network:
    driver: bridge
